Repository cartercsm9/codeCrafters, pull requests merged in 2024-04, with the labels that each got.

#96 added m4 document to requirements folder
  requirements/COSC 310 - M4.pdf
Labels: documentation

#95 Completed displaying historical weather data as a graph
  WebContent/app.js
  WebContent/routes/chart.js
  WebContent/views/historyPage.ejs
  WebContent/views/home.ejs
Labels: enhancement

#113 fixed problem where graphs wouldnt align dates dynamically. And furth…
  WebContent/public/charts.js
  WebContent/public/css/historyPage.css
  WebContent/views/historyPage.ejs
Labels: bug, enhancement

#120 Completed draft summary for M5
  requirements/M5 Completed Project Summary.txt
Labels: documentation

#123 server refressh
  WebContent/database.js
  WebContent/routes/notifications.js
  WebContent/routes/weather.js
  WebContent/server.js
Labels: bug, enhancement

#124 finished weather email alerts
  Dockerfile
  WebContent/app.js
  WebContent/ddl/init.sql
  WebContent/package.json
  WebContent/routes/notifications.js
  WebContent/views/NewYork.jpg
  WebContent/views/admin.ejs
  WebContent/views/alerts.ejs
  WebContent/views/historyPage.ejs
  WebContent/views/home.ejs
  WebContent/views/london.jpeg
Labels: enhancement
